import { Opportunity } from "@/types";

// ─────────────────────────────────────────────────────────────────────────────
// DUMMY SEED DATA — 15 opportunities across all 11 categories
// Used for development. Replace with real Firestore data in production.
// ─────────────────────────────────────────────────────────────────────────────

export const DUMMY_OPPORTUNITIES: Opportunity[] = [
  {
    id: "opp-001",
    title: "Summer Research Internship in Quantum Physics",
    organisation: "Indian Institute of Science (IISc)",
    subtitle: "8-week hands-on quantum computing research program for undergraduates",
    description: "<p>Join IISc's Department of Physics for an intensive 8-week summer research internship. Work alongside faculty and PhD scholars on cutting-edge quantum computing and condensed matter physics experiments.</p><p>Interns will receive a stipend of ₹15,000/month, accommodation assistance, and a completion certificate.</p><ul><li>Project areas: Quantum entanglement, Bose-Einstein condensates, Superconductivity</li><li>Weekly seminars with faculty</li><li>Final project presentation</li></ul>",
    eligibility: "3rd/4th year B.Sc. or B.Tech students with Physics or related background. CGPA ≥ 7.5 preferred.",
    deadline: "2025-12-15",
    applyLink: "https://iisc.ac.in",
    category: "physics",
    tags: ["internship", "summer", "research", "stipend", "quantum", "undergraduate"],
    postedAt: "2025-10-01",
    updatedAt: "2025-10-01",
    isTrending: true,
    views: 1240,
  },
  {
    id: "opp-002",
    title: "Google Summer of Code 2025",
    organisation: "Google",
    subtitle: "Global program connecting students with open source organisations",
    description: "<p>Google Summer of Code (GSoC) is a global, online program focused on bringing new contributors into open source software development. GSoC contributors work with an open source organization on a 12+ week programming project.</p><ul><li>Stipend: $1500–$6600 USD depending on project size and country</li><li>Mentor from the organisation assigned</li><li>Work remotely from anywhere</li></ul>",
    eligibility: "Anyone 18+ who is a student or new open-source contributor. Beginners welcome.",
    deadline: "2025-11-30",
    applyLink: "https://summerofcode.withgoogle.com",
    category: "sde",
    tags: ["open-source", "remote", "stipend", "google", "gsoc", "coding"],
    postedAt: "2025-09-15",
    updatedAt: "2025-09-20",
    isTrending: true,
    views: 3800,
  },
  {
    id: "opp-003",
    title: "ICMR Short-Term Studentship 2025",
    organisation: "Indian Council of Medical Research",
    subtitle: "Short-term research project in biomedical sciences for medical students",
    description: "<p>ICMR offers Short-Term Studentships (STS) to medical and dental students to inculcate a research culture. Selected students carry out a research project of 2 months duration under the supervision of a recognised guide.</p><p>Stipend: ₹10,000 for 2 months. Certificate of completion provided.</p>",
    eligibility: "MBBS/BDS/B.Sc. Nursing students in 2nd year or above. Students enrolled in Indian medical institutions.",
    deadline: "2025-12-31",
    applyLink: "https://icmr.nic.in/sts",
    category: "biology",
    tags: ["medical", "research", "stipend", "biomedical", "short-term", "icmr"],
    postedAt: "2025-09-01",
    updatedAt: "2025-09-01",
    isTrending: false,
    views: 980,
  },
  {
    id: "opp-004",
    title: "Goldman Sachs Engineering Campus Hiring Program",
    organisation: "Goldman Sachs",
    subtitle: "Technology internship and full-time roles for engineering students",
    description: "<p>Goldman Sachs engineering campus program offers internship and analyst roles across engineering, technology, and quantitative research divisions. Interns work on live projects impacting global financial markets.</p><ul><li>Duration: 10-week summer internship</li><li>Locations: Bengaluru, Mumbai, Hyderabad</li><li>Conversion to full-time offer possible</li></ul>",
    eligibility: "B.Tech/M.Tech/MCA in CS, IT, or related fields. Graduating 2026/2027. Strong programming skills required.",
    deadline: "2025-11-15",
    applyLink: "https://goldmansachs.com/careers",
    category: "finance",
    tags: ["internship", "fintech", "engineering", "campus", "stipend", "banking"],
    postedAt: "2025-09-10",
    updatedAt: "2025-09-10",
    isTrending: true,
    views: 2100,
  },
  {
    id: "opp-005",
    title: "DAAD WISE Scholarship 2025",
    organisation: "DAAD Germany",
    subtitle: "Research internship in Germany for Indian engineering/science students",
    description: "<p>The DAAD Working Internships in Science and Engineering (WISE) scholarship enables engineering and science students to undertake research internships at top German universities and research institutes.</p><p>Scholarship: €934/month + travel allowance + health insurance.</p>",
    eligibility: "Indian nationals enrolled in B.Tech/B.E./B.Sc. (3rd or 4th year). CGPA ≥ 8.5. Above-average English proficiency.",
    deadline: "2025-10-31",
    applyLink: "https://daad.de/en/study-and-research-in-germany/scholarships/daad-wise-scholarship/",
    category: "engineering",
    tags: ["scholarship", "germany", "international", "research", "daad", "funded"],
    postedAt: "2025-08-01",
    updatedAt: "2025-08-01",
    isTrending: true,
    views: 4200,
  },
  {
    id: "opp-006",
    title: "RBI Young Scholars Award Scheme",
    organisation: "Reserve Bank of India",
    subtitle: "Economics scholarship for undergraduate students in Indian colleges",
    description: "<p>The RBI Young Scholars Award Scheme provides scholarships to meritorious students pursuing undergraduate degree courses in any discipline from select colleges. Selected scholars also get summer internship opportunities at RBI.</p><p>Scholarship amount: ₹2 lakh for 3-year course.</p>",
    eligibility: "Students in 1st year of undergraduate programs (any stream). Scored ≥ 85% in Class 12. Indian nationals only.",
    deadline: "2025-12-20",
    applyLink: "https://rbi.org.in",
    category: "economics",
    tags: ["scholarship", "rbi", "economics", "undergraduate", "banking", "government"],
    postedAt: "2025-09-25",
    updatedAt: "2025-09-25",
    isTrending: false,
    views: 750,
  },
  {
    id: "opp-007",
    title: "Kaggle Data Science Competition — Climate Change",
    organisation: "Kaggle / Google",
    subtitle: "Global data science competition with ₹15 lakh prize pool",
    description: "<p>Participate in Kaggle's flagship climate change prediction challenge. Use satellite data, time-series analysis, and machine learning to model climate trends. Open to individuals and teams of up to 5.</p><p>Prize pool: $20,000. Top performers get fast-tracked interviews at Google, Meta, and partner companies.</p>",
    eligibility: "Open to all students and professionals worldwide. Team size: 1–5 members.",
    deadline: "2025-11-20",
    applyLink: "https://kaggle.com/competitions",
    category: "data-science",
    tags: ["competition", "machine-learning", "remote", "prize", "kaggle", "climate"],
    postedAt: "2025-09-05",
    updatedAt: "2025-09-05",
    isTrending: true,
    views: 5600,
  },
  {
    id: "opp-008",
    title: "PM Internship Scheme 2025",
    organisation: "Government of India",
    subtitle: "12-month internship in top 500 Indian companies with ₹5000/month stipend",
    description: "<p>The PM Internship Scheme provides valuable work experience to youth aged 21–24 in top companies across India. The government provides ₹4,500/month and companies add ₹500/month as their share.</p><p>One-time assistance of ₹6,000 for incidental expenses. Certificate issued by the Ministry of Corporate Affairs.</p>",
    eligibility: "Indian citizens aged 21–24. Not engaged in full-time employment or full-time education. From families with income ≤ ₹8 lakh/year.",
    deadline: "2025-11-25",
    applyLink: "https://pminternship.mca.gov.in",
    category: "government",
    tags: ["government", "internship", "stipend", "india", "corporate", "youth"],
    postedAt: "2025-10-01",
    updatedAt: "2025-10-01",
    isTrending: true,
    views: 8900,
  },
  {
    id: "opp-009",
    title: "SRFP — Summer Research Fellowship Programme",
    organisation: "Indian Academy of Sciences",
    subtitle: "Prestigious summer research fellowship across all science disciplines",
    description: "<p>The IAS Summer Research Fellowship Programme (SRFP) is jointly conducted by the three national science academies: IAS, INSA, and NASI. Students work in the laboratory of an elected Fellow of the academies.</p><p>Fellowship: ₹10,000/month + travel (TA/DA).</p>",
    eligibility: "Students in 1st or 2nd year of B.Sc./B.S./B.E./B.Tech. or 1st year of M.Sc./M.S./M.E./M.Tech. with consistently good academic record.",
    deadline: "2025-11-15",
    applyLink: "https://www.ias.ac.in/Initiatives/Summer_Research_Fellowship",
    category: "research",
    tags: ["fellowship", "research", "stipend", "science", "ias", "summer"],
    postedAt: "2025-09-01",
    updatedAt: "2025-09-01",
    isTrending: false,
    views: 2300,
  },
  {
    id: "opp-010",
    title: "Morgan Stanley Campus Ambassador Program",
    organisation: "Morgan Stanley",
    subtitle: "MBA internship and ambassador program for top B-school students",
    description: "<p>Morgan Stanley's campus ambassador and summer internship program for MBA students provides exposure to investment banking, equity research, and asset management. Selected candidates work on live deals and client projects.</p>",
    eligibility: "First-year MBA students at IIMs, XLRI, FMS, ISB, or top-ranked B-schools. Finance background preferred.",
    deadline: "2025-12-01",
    applyLink: "https://morganstanley.com/careers",
    category: "mba",
    tags: ["mba", "internship", "investment-banking", "finance", "iim", "summer"],
    postedAt: "2025-09-20",
    updatedAt: "2025-09-20",
    isTrending: false,
    views: 1400,
  },
  {
    id: "opp-011",
    title: "Chemistry Olympiad Training Camp — HBCSE",
    organisation: "Homi Bhabha Centre for Science Education",
    subtitle: "National training camp for International Chemistry Olympiad selection",
    description: "<p>HBCSE conducts orientation-cum-selection camps for students who qualify in the National Standard Examination in Chemistry (NSEC). Top performers are selected to represent India at the International Chemistry Olympiad (IChO).</p>",
    eligibility: "Students who have qualified NSEC. Must be in Class 11 or 12. Indian nationals only.",
    deadline: "2025-12-10",
    applyLink: "https://hbcse.tifr.res.in",
    category: "chemistry",
    tags: ["olympiad", "competition", "chemistry", "national", "hbcse", "school"],
    postedAt: "2025-09-15",
    updatedAt: "2025-09-15",
    isTrending: false,
    views: 620,
  },
  {
    id: "opp-012",
    title: "Smart India Hackathon 2025",
    organisation: "Ministry of Education, Government of India",
    subtitle: "National hackathon to solve real government and industry problem statements",
    description: "<p>Smart India Hackathon (SIH) is a nationwide initiative to provide students a platform to solve pressing problems that affect daily lives. Teams of 6 students compete over 36 hours to build solutions for problem statements submitted by ministries, departments, and industries.</p><p>Prize: ₹1,00,000 per winning team per problem statement.</p>",
    eligibility: "All students enrolled in any UG/PG program in India. Team of exactly 6 members required. Must register through your institute's nodal centre.",
    deadline: "2025-10-31",
    applyLink: "https://sih.gov.in",
    category: "sde",
    tags: ["hackathon", "government", "team", "prize", "india", "engineering"],
    postedAt: "2025-08-15",
    updatedAt: "2025-08-20",
    isTrending: true,
    views: 12000,
  },
  {
    id: "opp-013",
    title: "Mitacs Globalink Research Internship",
    organisation: "Mitacs Canada",
    subtitle: "12-week research internship at Canadian universities for international students",
    description: "<p>The Mitacs Globalink Research Internship is a competitive initiative for outstanding students from partner countries. From May to October each year, undergraduates complete a 12-week research project at a Canadian university under the supervision of a Canadian professor.</p><p>Fully funded: Round-trip airfare, accommodation, and $10,000 CAD stipend.</p>",
    eligibility: "Undergraduate students (3rd year or above) from India. CGPA ≥ 3.0/4.0. Proficiency in English. Min. 2 courses completed in proposed research area.",
    deadline: "2025-09-30",
    applyLink: "https://www.mitacs.ca/globalink",
    category: "research",
    tags: ["canada", "international", "fellowship", "funded", "mitacs", "undergraduate"],
    postedAt: "2025-07-01",
    updatedAt: "2025-07-01",
    isTrending: true,
    views: 6700,
  },
  {
    id: "opp-014",
    title: "Microsoft Imagine Cup 2025",
    organisation: "Microsoft",
    subtitle: "Global student technology competition with Azure AI as core platform",
    description: "<p>Microsoft Imagine Cup is Microsoft's premier student technology competition. This year's theme is AI for Good — build solutions that address a real-world problem using Microsoft Azure AI services.</p><p>Grand Prize: $85,000 USD + Azure credits + mentorship from Microsoft executives.</p>",
    eligibility: "Students 16+ enrolled in any accredited college or university. Teams of 1–3. No nationality restrictions.",
    deadline: "2025-12-31",
    applyLink: "https://imaginecup.microsoft.com",
    category: "sde",
    tags: ["hackathon", "ai", "microsoft", "azure", "competition", "global", "prize"],
    postedAt: "2025-09-01",
    updatedAt: "2025-09-05",
    isTrending: false,
    views: 3100,
  },
  {
    id: "opp-015",
    title: "Teach for India Fellowship",
    organisation: "Teach For India",
    subtitle: "2-year paid teaching fellowship in under-resourced schools",
    description: "<p>The Teach For India Fellowship is a 2-year leadership development programme where outstanding graduates teach full-time in under-resourced classrooms. Fellows develop exceptional leadership and problem-solving skills while making a tangible impact on educational equity.</p><p>Monthly stipend: ₹17,000–₹28,000 (scales by year and city). Health insurance provided.</p>",
    eligibility: "Recent graduates (within 3 years) from any field. Indian citizens. Strong academic record. No prior teaching experience needed.",
    deadline: "2025-11-30",
    applyLink: "https://teachforindia.org",
    category: "government",
    tags: ["fellowship", "education", "ngo", "paid", "leadership", "2-year"],
    postedAt: "2025-08-10",
    updatedAt: "2025-08-10",
    isTrending: false,
    views: 890,
  },
];
